### ISSUE TITLE
What part should I modify to make it only generate albedo map. 

### ISSUE THREAD

**Issue by cloudhan** [unibas-gravis/parametric-face-image-generator#1]
What I want to get is simply the diffuse albedo map (aka the base color without illumination, but aligned with the the rendered image), but after inspect into the code, I can only find function invoke the renderer but not the render code. 

Would you mind point me out which part of code should I modify to meet my requirement?

**Comment by BernhardEgger** [comment]
Hi Cloudhan,

the easiest way to do so is to render the face with ambient white illumination:
use SphericalHarmonicsLight.ambientWhite instead of the current light setting

The renderer is part of the imported scalismo-faces software framework: https://github.com/unibas-gravis/scalismo-faces - to get an idea of its capabilities we made a tutorial: http://gravis.dmi.unibas.ch/PMM/lectures/fitting/

Best
Bernhard
