### ISSUE TITLE
Could not find or load main class: faces.apps.ControlledFaces

### ISSUE THREAD

**Issue by yushuinanrong** [unibas-gravis/parametric-face-image-generator#20]
Hi,

First of all, thanks for sharing this software. It looks interesting and I want to explore it a bit more. 
However, after I installing the dependencies as illustrated, I could not run the javascript using the command 
```
java -Xmx2g -cp generator.jar faces.apps.ControlledFaces -c data/config_files/example_config_controlled.json
```
I keep getting the error message:
```
Could not find or load main class: faces.apps.ControlledFaces
```
I apology for my limited background in Java and not capable to figure out a way to get over this error. Please let me know if you have any idea what the cause is.

Best regards,
Melo

**Comment by BernhardEgger** [comment]
Hi Melo,

are you executing this command in the folder where your generator.jar is located?
I get this message when I execute the command in a folder where no generator.jar file is existing.

Best
Bernhard

**Comment by yushuinanrong** [comment]
Hi @BernhardEgger 
I really appreciate your quick response. 
I thought generator.jar is a built-in part of this software. But seems it is not. 
Could you point me to some resource that I can learn to create this .jar file?

Bests,
Melo

**Comment by BernhardEgger** [comment]
Hi Melo,

it looks like you downloaded the sources instead of the built software...
As stated in the readme file, please `download jar and config file under release`
That would be here:
https://github.com/unibas-gravis/parametric-face-image-generator/releases

Please also follow the other necessary steps in the readme file to be able to render images.

Best
Bernhard

**Comment by yushuinanrong** [comment]
Hi @BernhardEgger 
Thank you for your kind tips! I got the software running smoothly.
I found when generating a face image, the software also generates a .csv file containing a number of entries in the first row (521 columns in my case when generating a 100x100 image). Are these numbers the labels for pose angles, illumination, and etc? 

Best regards,
Melo

**Comment by BernhardEgger** [comment]
Hi Melo,
the csv file contains parts of the data of the rps file.
This method here generates the csv from the RenderParameters:
`  // method to write csv file of parameters
  def writeCSV(rps: RenderParameter, file: File): Unit = {

    val vPose: DenseVector[Double] = DenseVector(
      rps.pose.yaw,
      rps.pose.pitch,
      rps.pose.roll,
      rps.pose.translation.x,
      rps.pose.translation.y,
      rps.pose.translation.z
    )
    val vCamera: DenseVector[Double] = DenseVector(
      rps.camera.principalPoint.x,
      rps.camera.principalPoint.y,
      rps.camera.focalLength,
      rps.camera.sensorSize.x,
      rps.camera.sensorSize.y)
    val vMoMo: DenseVector[Double] = DenseVector((rps.momo.shape ++ rps.momo.color ++ rps.momo.expression).toArray)
    val vLight: DenseVector[Double] = rps.environmentMap.toBreezeVector

    val vParam = DenseVector.vertcat(vPose, vCamera, vMoMo, vLight)

    breeze.linalg.csvwrite(file, vParam.toDenseMatrix)
}`

I'm closing this issue now - since it is not relating to a bug in our software.
For general questions please use our Mailing List https://groups.google.com/forum/#!forum/scalismo-faces

Best
Bernhard

**Comment by BernhardEgger** [comment]
``

**Comment by yushuinanrong** [comment]
Hi @BernhardEgger 

Thank you very much!

Melo
