### ISSUE TITLE
Another data

### ISSUE THREAD

**Issue by boomberung** [unibas-gravis/parametric-face-image-generator#28]
Can i use it with another data, not basel?

**Comment by BernhardEgger** [comment]
Hi boomberung,

thank you for your interest in the parametric-face-image-generator.

Yes, it is programmed in a way such that it can handel various models, including other models or even non-face models.
The model just has to be in the Statismo file format and you might have to align the reference or change the camera settings. Some settings might be specific to the Basel Face Model (e.g. those based on landmarks). But you could craft those in your other model.

Since this is question, not an issue I close it here

Please use our google group for further questions:
https://groups.google.com/forum/#!forum/scalismo-faces

Best
Bernhard
